/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.IssuesBusiness;
import domain.Issue;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author william
 */
public class buscarIssues extends javax.swing.JInternalFrame {
    private  ArrayList<Issue>listaIssues;
    private int cod_tarea;

    /**
     * Creates new form buscarTareas
     */
    public buscarIssues(int id) throws SQLException {
        initComponents();
        listaIssues=new ArrayList();
        cod_tarea=id;
        cargarTabla();
    }

    
    
    
    
    
    public void cargarTabla() throws SQLException{
        jTable.setVisible(true);
        DefaultTableModel modelo =new DefaultTableModel();
        String datos[]=new String[5];
        
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("cod_tarea");
        
        IssuesBusiness issueBl= new IssuesBusiness();
        listaIssues=issueBl.obtener(cod_tarea);
        
        for(Issue i:listaIssues){
            datos[0]=String.valueOf(i.getId());
            datos[1]=i.getTitulo();
            datos[2]=i.getDescripcion();
            datos[3]=String.valueOf(i.getId_tarea());
            modelo.addRow(datos);
        }
        
        jTable.setModel(modelo);
    }
    
    public void buscar() throws SQLException, Exception{
        ArrayList<Issue>listaIssues=new ArrayList();
        
        DefaultTableModel modelo =new DefaultTableModel();
        
        String datos[]=new String[5];
        
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Usuario");
        
        IssuesBusiness ibl = new IssuesBusiness();
        Issue issue=new Issue();
        issue.setId(Integer.parseInt(txtId.getText()));
        issue.setId_tarea(cod_tarea);
        issue=ibl.buscar(issue);
        listaIssues.add(issue);
        
        for(Issue i:listaIssues){
            datos[0]=String.valueOf(i.getId());
            datos[1]=i.getTitulo();
            datos[2]=i.getDescripcion();
            datos[3]=String.valueOf(i.getId_tarea());
            modelo.addRow(datos);
        }
        
        jTable.setModel(modelo);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtId))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try {
            buscar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
