/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.ProyectosBusiness;
import domain.Proyecto;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author william
 */
public class buscarProyectos extends javax.swing.JInternalFrame {
    private  ArrayList<Proyecto>listaProyectos;
    private int id_usuario;

    /**
     * Creates new form buscarProyectos
     */
    public buscarProyectos(int id) throws SQLException {
        initComponents();
        listaProyectos=new ArrayList();
        id_usuario=id;
        cargarTabla();
    }
    
    public  void cargarTabla() throws SQLException{
        jTable.setVisible(true);
        DefaultTableModel modelo =new DefaultTableModel();
        String datos[]=new String[5];
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Usuario");
        
        ProyectosBusiness pbl = new ProyectosBusiness();
        listaProyectos=pbl.obtener(id_usuario);
        
        for(Proyecto p:listaProyectos){
            datos[0]=String.valueOf(p.getId());
            datos[1]=p.getNombre();
            datos[2]=p.getDetalle();
            datos[3]=String.valueOf(p.getId_usuario());
            modelo.addRow(datos);
        }
        
        jTable.setModel(modelo);
        
        
        
    }
    
    public void buscar() throws SQLException, Exception{
        ArrayList<Proyecto>listaProyecto=new ArrayList();
        
        DefaultTableModel modelo =new DefaultTableModel();
        
        String datos[]=new String[5];
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Usuario");
        
        ProyectosBusiness pbl = new ProyectosBusiness();
        Proyecto proyecto=new Proyecto();
        proyecto.setId(Integer.parseInt(txtId.getText()));
        proyecto.setId_usuario(id_usuario);
        proyecto=pbl.buscar(proyecto);
        listaProyecto.add(proyecto);
        
        for(Proyecto p:listaProyecto){
            datos[0]=String.valueOf(p.getId());
            datos[1]=p.getNombre();
            datos[2]=p.getDetalle();
            datos[3]=String.valueOf(p.getId_usuario());
            modelo.addRow(datos);
        }
        
        jTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btBuscar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try {
            buscar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
