/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.TareasBusiness;
import domain.Tarea;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author william
 */
public class buscarTareas extends javax.swing.JInternalFrame {
    private  ArrayList<Tarea>listaTareas;
    private int cod_Proyecto;

    /**
     * Creates new form buscarTareas
     */
    public buscarTareas(int id) throws SQLException {
        initComponents();
        listaTareas=new ArrayList();
        cod_Proyecto=id;
        cargarTabla();
    }

    
    
    
    
    
    public void cargarTabla() throws SQLException{
        jTable.setVisible(true);
        DefaultTableModel modelo =new DefaultTableModel();
        String datos[]=new String[5];
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("cod_Proyecto");
        
        TareasBusiness tareaBl= new TareasBusiness();
        listaTareas=tareaBl.obtener(cod_Proyecto);
        
        for(Tarea t:listaTareas){
            datos[0]=String.valueOf(t.getId());
            datos[1]=t.getNombre();
            datos[2]=t.getDescripcion();
            datos[3]=String.valueOf(t.getId_Proyecto());
            modelo.addRow(datos);
        }
        
        jTable.setModel(modelo);
    }
    
    public void buscar() throws SQLException, Exception{
        ArrayList<Tarea>listaTareas=new ArrayList();
        
        DefaultTableModel modelo =new DefaultTableModel();
        
        String datos[]=new String[5];
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Usuario");
        
        TareasBusiness tbl = new TareasBusiness();
        Tarea tarea=new Tarea();
        tarea.setId(Integer.parseInt(txtId.getText()));
        tarea.setId_Proyecto(cod_Proyecto);
        tarea=tbl.buscar(tarea);
        listaTareas.add(tarea);
        
        for(Tarea t:listaTareas){
            datos[0]=String.valueOf(t.getId());
            datos[1]=t.getNombre();
            datos[2]=t.getDescripcion();
            datos[3]=String.valueOf(t.getId_Proyecto());
            modelo.addRow(datos);
        }
        
        jTable.setModel(modelo);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btBuscar)
                .addGap(18, 18, 18)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try {
            buscar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
