/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.ProyectosBusiness;
import domain.Issue;
import domain.Proyecto;
import domain.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author william
 */
public class QA extends javax.swing.JFrame {
    private Usuario usuario;
    

    /**
     * Creates new form QA
     */
    public QA() {
        initComponents();
        
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        btCerrarSeccion = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuProyectos = new javax.swing.JMenu();
        ItemAgregar = new javax.swing.JMenuItem();
        ItemActualizar = new javax.swing.JMenuItem();
        ItemBorrar = new javax.swing.JMenuItem();
        ItemBuscar = new javax.swing.JMenuItem();
        MenuTareas = new javax.swing.JMenu();
        AgregarTarea = new javax.swing.JMenuItem();
        actualizarTarea = new javax.swing.JMenuItem();
        VerTareas = new javax.swing.JMenuItem();
        MenuIssues = new javax.swing.JMenu();
        agregarIssues = new javax.swing.JMenuItem();
        actualizarIssues = new javax.swing.JMenuItem();
        BuscarIssues = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        MenuInicio.setText("inicio");

        btCerrarSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete_user.png"))); // NOI18N
        btCerrarSeccion.setText("cerrar seccion");
        btCerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSeccionActionPerformed(evt);
            }
        });
        MenuInicio.add(btCerrarSeccion);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuInicio.add(jMenuItem1);

        jMenuBar1.add(MenuInicio);

        MenuProyectos.setText("Proyectos");

        ItemAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/folder_new.png"))); // NOI18N
        ItemAgregar.setText("Nuevo proyecto");
        ItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarActionPerformed(evt);
            }
        });
        MenuProyectos.add(ItemAgregar);

        ItemActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit.png"))); // NOI18N
        ItemActualizar.setText("actualizar");
        ItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemActualizarActionPerformed(evt);
            }
        });
        MenuProyectos.add(ItemActualizar);

        ItemBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editdelete.png"))); // NOI18N
        ItemBorrar.setText("borrar");
        ItemBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBorrarActionPerformed(evt);
            }
        });
        MenuProyectos.add(ItemBorrar);

        ItemBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        ItemBuscar.setText("buscar");
        ItemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarActionPerformed(evt);
            }
        });
        MenuProyectos.add(ItemBuscar);

        jMenuBar1.add(MenuProyectos);

        MenuTareas.setText("Tareas");

        AgregarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/document-add-icon.png"))); // NOI18N
        AgregarTarea.setText("Agregar tarea");
        AgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTareaActionPerformed(evt);
            }
        });
        MenuTareas.add(AgregarTarea);

        actualizarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit.png"))); // NOI18N
        actualizarTarea.setText("actualizar");
        actualizarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTareaActionPerformed(evt);
            }
        });
        MenuTareas.add(actualizarTarea);

        VerTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        VerTareas.setText("buscar tareas");
        VerTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTareasActionPerformed(evt);
            }
        });
        MenuTareas.add(VerTareas);

        jMenuBar1.add(MenuTareas);

        MenuIssues.setText("Issues");

        agregarIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit_add.png"))); // NOI18N
        agregarIssues.setText("agregar issue");
        agregarIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIssuesActionPerformed(evt);
            }
        });
        MenuIssues.add(agregarIssues);

        actualizarIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit.png"))); // NOI18N
        actualizarIssues.setText("actualizar");
        actualizarIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarIssuesActionPerformed(evt);
            }
        });
        MenuIssues.add(actualizarIssues);

        BuscarIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/find.png"))); // NOI18N
        BuscarIssues.setText("Ver isuues");
        BuscarIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIssuesActionPerformed(evt);
            }
        });
        MenuIssues.add(BuscarIssues);

        jMenuBar1.add(MenuIssues);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarActionPerformed
        agregarProyectos pro =new agregarProyectos();
        pro.setVisible(true);
        pro.setId_user(usuario.getId());
        pro.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
        jDesktopPane1.add(pro);
        
    }//GEN-LAST:event_ItemAgregarActionPerformed

    private void ItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarActionPerformed
        try {
            buscarProyectos bp=new buscarProyectos(usuario.getId());
            bp.setVisible(true);
            bp.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
            jDesktopPane1.add(bp);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_ItemBuscarActionPerformed

    private void ItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemActualizarActionPerformed
        ActualizarProyectos pro=new ActualizarProyectos();
        pro.setVisible(true);
        pro.setId_user(usuario.getId());
        pro.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
        jDesktopPane1.add(pro);
    }//GEN-LAST:event_ItemActualizarActionPerformed

    private void ItemBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBorrarActionPerformed
        try {
            int id =Integer.parseInt(JOptionPane.showInputDialog("Digite el cod de proyecto que desea borrar"));
            Proyecto proyecto= new Proyecto();
            proyecto.setId(id);
            ProyectosBusiness pbl = new ProyectosBusiness();
            pbl.borrar(proyecto);
            JOptionPane.showMessageDialog(rootPane, "Proyecto borrado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ItemBorrarActionPerformed

    private void AgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTareaActionPerformed
        try {
            agregarTareas t = new agregarTareas(usuario.getId());
            
            t.setVisible(true);
            t.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
            jDesktopPane1.add(t);
        } catch (SQLException ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            
        
        
    }//GEN-LAST:event_AgregarTareaActionPerformed

    private void VerTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTareasActionPerformed
        try {
            buscarTareas bt = new buscarTareas(usuario.getId());
            bt.setVisible(true);
            bt.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
            jDesktopPane1.add(bt);
        } catch (SQLException ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        }
                
           
        
    }//GEN-LAST:event_VerTareasActionPerformed

    private void btCerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSeccionActionPerformed
        Loggin log=new Loggin();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCerrarSeccionActionPerformed

    private void agregarIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIssuesActionPerformed
        int cod_tarea=Integer.parseInt(JOptionPane.showInputDialog("digite el cod del la tarea"));
        agregarIssues issues = new agregarIssues();
        issues.setVisible(true);
        issues.setCod_tarea(cod_tarea);
        issues.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
        
        jDesktopPane1.add(issues);
        
        
    }//GEN-LAST:event_agregarIssuesActionPerformed

    private void actualizarIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarIssuesActionPerformed
        int cod_tarea=Integer.parseInt(JOptionPane.showInputDialog("digite el cod del la tarea"));
        Issue i= new Issue();
        
        ActualizarIssues issues=new ActualizarIssues();
        issues.setVisible(true);
        issues.setCod_tarea(cod_tarea);
        issues.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
        jDesktopPane1.add(issues);
    }//GEN-LAST:event_actualizarIssuesActionPerformed

    private void BuscarIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIssuesActionPerformed
        try {
            int cod_tarea=Integer.parseInt(JOptionPane.showInputDialog("digite el cod del la tarea"));
            buscarIssues bi=new buscarIssues(cod_tarea);
            bi.setVisible(true);
            bi.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
            jDesktopPane1.add(bi);
        } catch (SQLException ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarIssuesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void actualizarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTareaActionPerformed
        try {
            
            ActualizarTareas act= new ActualizarTareas(usuario.getId());
            act.setVisible(true);
            act.setTitle(usuario.getNombre()+" "+usuario.getPuesto());
            jDesktopPane1.add(act);
        } catch (SQLException ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(QA.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
            
        
    }//GEN-LAST:event_actualizarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QA().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarTarea;
    private javax.swing.JMenuItem BuscarIssues;
    private javax.swing.JMenuItem ItemActualizar;
    private javax.swing.JMenuItem ItemAgregar;
    private javax.swing.JMenuItem ItemBorrar;
    private javax.swing.JMenuItem ItemBuscar;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenu MenuIssues;
    private javax.swing.JMenu MenuProyectos;
    private javax.swing.JMenu MenuTareas;
    private javax.swing.JMenuItem VerTareas;
    private javax.swing.JMenuItem actualizarIssues;
    private javax.swing.JMenuItem actualizarTarea;
    private javax.swing.JMenuItem agregarIssues;
    private javax.swing.JMenuItem btCerrarSeccion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
